version: 2
jobs:
  build:
    working_directory: ~/emberobserver/client
    docker:
      - image: circleci/node:10.14-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - run: COVERAGE=true yarn test
      - run: bash <(curl -s https://codecov.io/bash)
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "beta" ]; then
              sudo apt install -y rsync
              ssh-keyscan emberobserver.com >> ~/.ssh/known_hosts
              PATH="~/emberobserver/client/node_modules/.bin:$PATH" ember deploy beta --activate
            fi
